stages:
  - deploy_live

variables:
  KUBECONFIG: /etc/deploy/config

deploy_live:
  stage: deploy_live
  image: dwdraju/gke-kubectl-docker
  only:
    - master
  script:
    - echo $KUBE_NAMESPACE
    - echo $KUBE_URL
    - echo $KUBECONFIG
    - cat $KUBECONFIG
    - echo $KUBE_TOKEN
    - kubectl get nodes

