stages:
  - deploy_live

deploy_live:
  image:
    name: dwdraju/gke-kubectl-docker
    entrypoint: [""]
  stage: deploy_live
  only:
    - master
  script:
    - kubectl config set-cluster k8s --server="$CLUSTER_ADDRESS"
    - echo $CA_AUTH_DATA > kubernetes.ca.crt
    - kubectl config set-cluster k8s --certificate-authority=./kubernetes.ca.crt
    - kubectl config set-credentials gitlab-service-account --token=$K8S_TOKEN
    - kubectl config set-context default --cluster=k8s --user=gitlab-admin --namespace=default
    - kubectl get nodes
    - kubectl config use-context default

