stages:
  - deploy_live

variables:
  KUBECONFIG: /etc/deploy/config

deploy_live:
  stage: deploy_live
  image: dwdraju/gke-kubectl-docker
  only:
    - master
  script:
    - mkdir -p /etc/deploy
    - echo -n $KUBE_CONFIG | base64 -d > $HOME/.kube/config
    - kubectl get nodes

